function results = run_phase1_blue_acceptance(simscape_plant_model, simscape_plant_input)
%RUN_PHASE1_BLUE_ACCEPTANCE Phase-1 acceptance for Simscape blue-library plant.
%
% Usage:
%   run_phase1_blue_acceptance('your_plant_model_name')
%   run_phase1_blue_acceptance('your_plant_model_name', 'gates_6')
%   run_phase1_blue_acceptance   % uses env PMSM_SIMSCAPE_PLANT_MODEL
%
% Acceptance rule in phase-1: simulation completes without runtime errors.

script_dir = fileparts(mfilename('fullpath'));
matlab_dir = fullfile(script_dir, '..');
simscape_dir = fullfile(matlab_dir, 'simscape');

addpath(matlab_dir);
addpath(script_dir);
addpath(simscape_dir);
rehash path;

if exist('pmsm_foc_simscape', 'file') ~= 2
    error(['Cannot find pmsm_foc_simscape on MATLAB path.\n' ...
           'Run setup_project first, or ensure matlab/simscape is on path.']);
end

if nargin < 1 || isempty(simscape_plant_model)
    simscape_plant_model = strtrim(getenv('PMSM_SIMSCAPE_PLANT_MODEL'));
end

if nargin < 2 || isempty(simscape_plant_input)
    simscape_plant_input = 'gates_6';
end

if ~strcmpi(simscape_plant_input, 'duty_abc') && ~strcmpi(simscape_plant_input, 'gates_6')
    error('Unsupported simscape_plant_input: %s. Use duty_abc or gates_6.', simscape_plant_input);
end

if isempty(simscape_plant_model)
    error(['Missing simscape_plant_model.\n' ...
           'Call run_phase1_blue_acceptance(''your_model_name'') or set env PMSM_SIMSCAPE_PLANT_MODEL.']);
end

results = struct('name', {}, 'passed', {}, 'message', {});

cases = {
    struct( ...
        'name', 'speed_step_only', ...
        'overrides', struct( ...
            'ref_params', struct( ...
                'speed_ref', 1000, ...
                'speed_ramp_time', 0.1, ...
                'load_torque', 0.0, ...
                'load_step_time', 0.3, ...
                'id_ref', 0, ...
                'throttle_adc_before', 0, ...
                'throttle_adc_after', 2800, ...
                'throttle_step_time', 0.05, ...
                'throttle_torque_max', 0.2), ...
            'sim_params', struct( ...
                't_end', 0.5, ...
                'controller_mode', 'sfun', ...
                'iq_ref_source', 'throttle', ...
                'Ts_control', 1/12000, ...
                'Ts_speed', 1/1000, ...
                'Ts_throttle', 1/1000, ...
                'plant_mode', 'simscape_blue', ...
                'simscape_plant_input', simscape_plant_input, ...
                'simscape_plant_model', simscape_plant_model))), ...
    struct( ...
        'name', 'speed_and_load_step', ...
        'overrides', struct( ...
            'ref_params', struct( ...
                'speed_ref', 1000, ...
                'speed_ramp_time', 0.1, ...
                'load_torque', 0.1, ...
                'load_step_time', 0.3, ...
                'id_ref', 0, ...
                'throttle_adc_before', 0, ...
                'throttle_adc_after', 3400, ...
                'throttle_step_time', 0.05, ...
                'throttle_torque_max', 0.2), ...
            'sim_params', struct( ...
                't_end', 0.5, ...
                'controller_mode', 'sfun', ...
                'iq_ref_source', 'throttle', ...
                'Ts_control', 1/12000, ...
                'Ts_speed', 1/1000, ...
                'Ts_throttle', 1/1000, ...
                'plant_mode', 'simscape_blue', ...
                'simscape_plant_input', simscape_plant_input, ...
                'simscape_plant_model', simscape_plant_model))) ...
};

fprintf('=== Phase-1 Acceptance (Simscape BLUE + C++ S-Function) ===\n');
fprintf('Plant model: %s\n', simscape_plant_model);

for i = 1:numel(cases)
    c = cases{i};
    fprintf('\n[%d/%d] Running case: %s\n', i, numel(cases), c.name);

    try
        pmsm_foc_simscape(c.overrides);
        results(end + 1) = struct( ...
            'name', c.name, ...
            'passed', true, ...
            'message', 'simulation completed'); %#ok<AGROW>
        fprintf('  PASS: simulation completed\n');
    catch ME
        results(end + 1) = struct( ...
            'name', c.name, ...
            'passed', false, ...
            'message', ME.message); %#ok<AGROW>
        fprintf('  FAIL: %s\n', ME.message);
    end
end

all_passed = all([results.passed]);
if all_passed
    fprintf('\nAcceptance result: PASS\n');
else
    fprintf('\nAcceptance result: FAIL\n');
end
end
