function results = run_phase1_acceptance()
%RUN_PHASE1_ACCEPTANCE Minimal phase-1 acceptance runs for Simscape + C++ FOC.
%
% Acceptance rule in phase-1: simulation completes without runtime errors.

results = struct('name', {}, 'passed', {}, 'message', {});

cases = {
    struct( ...
        'name', 'speed_step_only', ...
        'overrides', struct( ...
            'ref_params', struct( ...
                'speed_ref', 1000, ...
                'speed_ramp_time', 0.1, ...
                'load_torque', 0.0, ...
                'load_step_time', 0.3, ...
                'id_ref', 0), ...
            'sim_params', struct('t_end', 0.5))), ...
    struct( ...
        'name', 'speed_and_load_step', ...
        'overrides', struct( ...
            'ref_params', struct( ...
                'speed_ref', 1000, ...
                'speed_ramp_time', 0.1, ...
                'load_torque', 0.1, ...
                'load_step_time', 0.3, ...
                'id_ref', 0), ...
            'sim_params', struct('t_end', 0.5))) ...
};

fprintf('=== Phase-1 Acceptance (Simscape + C++ S-Function) ===\n');

for i = 1:numel(cases)
    c = cases{i};
    fprintf('\n[%d/%d] Running case: %s\n', i, numel(cases), c.name);

    try
        pmsm_foc_simscape(c.overrides);
        results(end + 1) = struct( ...
            'name', c.name, ...
            'passed', true, ...
            'message', 'simulation completed'); %#ok<AGROW>
        fprintf('  PASS: simulation completed\n');
    catch ME
        results(end + 1) = struct( ...
            'name', c.name, ...
            'passed', false, ...
            'message', ME.message); %#ok<AGROW>
        fprintf('  FAIL: %s\n', ME.message);
    end
end

all_passed = all([results.passed]);
if all_passed
    fprintf('\nAcceptance result: PASS\n');
else
    fprintf('\nAcceptance result: FAIL\n');
end
end
